[package]
name = "dhcp_client"
version = "0.1.2"
edition = "2021"
description = "检查网络内有哪些DHCP服务器，向指定的DHCP服务器发送request请求，可以指定发送的请求次数，\n提示：不能使用无线网卡。"

[dependencies]
clap = { version = "4.5.26", features = ["derive"] }
dhcproto = "0.12.0"
pnet = "0.35.0"
rand = "0.8.5"
